--- 
jobs: 
  apitest: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    environment: 
      MAVEN_OPTS: "-Xmx3200m"
    steps: 
      - 
        at: ~/repo
        attach_workspace: ~
      - 
        run: 
          command: |
              mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
              git clone -b master git@github.com/maximinogomez/api-integration-tests.git
          name: "clone api-integration-tests"
      - 
        run: 
          command: |
              echo "configuring workspace"
              curl -O http://apache.spinellicreations.com/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
              unzip apache-maven-3.5.3-bin.zip
              echo $JAVA_HOME
              export PATH=./apache-maven-3.5.3/bin:$PATH
              echo $PATH
              apache-maven-3.5.3/bin/mvn -v
              apache-maven-3.5.3/bin/mvn compile -s settings.xml
          name: "compile api-tests"
          working_directory: ~/repo/api-integration-tests
      - 
        run: 
          command: "apache-maven-3.5.3/bin/mvn -B -s ./settings.xml test -Denvironment=plat\n"
          name: "run api-tests"
          working_directory: ~/repo/api-integration-tests
    working_directory: ~/repo
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    environment: 
      MAVEN_OPTS: "-Xmx3200m"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"pom.xml\" }}"
            - v1-dependencies-
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: "mvn compile"
    working_directory: ~/repo
version: 2
workflows: 
  build_test: 
    jobs: 
      - build
      - apitest
  version: 2
