# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      #- run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn compile

      # run tests!
      #- run: mvn integration-test
  apitest:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: clone engage-tests
          command: |
              mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
              git clone -b master git@github.com:PivotusVentures/engage-tests.git
      - run:
          name: compile api-tests
          working_directory: ~/repo/engage-tests/api-tests
          command: |
              echo "configuring workspace"
              curl -O http://apache.spinellicreations.com/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
              unzip apache-maven-3.5.3-bin.zip
              echo $JAVA_HOME
              export PATH=./apache-maven-3.5.3/bin:$PATH
              echo $PATH
              apache-maven-3.5.3/bin/mvn -v
              apache-maven-3.5.3/bin/mvn compile -s settings.xml
      - run:
          name: run api-tests
          working_directory: ~/repo/engage-tests/api-tests
          command: |

              apache-maven-3.5.3/bin/mvn -B -s ./settings.xml test -Denvironment=plat
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - apitest

